import { useState } from "react";
import { Building2, FileText, Star } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { GlassCard, Pill, SectionTitle, timeAgo } from "./primitives";
import { inr, inrCompact } from "@/lib/wms/actions";
import type { PurchaseOrder, WmsState } from "@/lib/wms/types";

function InvoiceBill({ po }: { po: PurchaseOrder }) {
  return (
    <div className="glass-2 rounded-2xl p-5 animate-rise">
      <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border pb-3">
        <div>
          <p className="font-display text-base font-semibold">Purchase Order Invoice</p>
          <p className="font-mono text-xs text-muted-foreground">{po.id}</p>
        </div>
        <div className="text-right text-xs">
          <p className="font-semibold">{po.vendorName}</p>
          <p className="font-mono text-muted-foreground">GSTIN: {po.gstin}</p>
          <p className="text-muted-foreground">{new Date(po.createdAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</p>
        </div>
      </div>
      <table className="mt-3 w-full text-xs">
        <thead className="text-muted-foreground">
          <tr className="text-left">
            <th className="py-1">Item</th>
            <th>SKU</th>
            <th className="text-right">Units</th>
            <th className="text-right">Rate</th>
            <th className="text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-t border-border">
            <td className="py-2">{po.item}</td>
            <td className="font-mono">{po.sku}</td>
            <td className="text-right font-mono">{po.units}</td>
            <td className="text-right font-mono">{inr(po.unitPrice)}</td>
            <td className="text-right font-mono">{inr(po.subtotal)}</td>
          </tr>
        </tbody>
      </table>
      <div className="mt-3 space-y-1 border-t border-border pt-3 text-xs">
        <div className="flex justify-between text-muted-foreground">
          <span>Subtotal</span>
          <span className="font-mono">{inr(po.subtotal)}</span>
        </div>
        <div className="flex justify-between text-muted-foreground">
          <span>IGST @ 18%</span>
          <span className="font-mono">{inr(po.gst)}</span>
        </div>
        <div className="flex justify-between text-sm font-semibold">
          <span>Total Payable</span>
          <span className="font-mono text-neon">{inr(po.total)}</span>
        </div>
      </div>
      <div className="mt-3 flex items-center justify-between">
        <Pill tone={po.status === "received" ? "emerald" : "cyan"}>{po.status}</Pill>
        <span className="text-[11px] text-muted-foreground">Auto-generated by Helix Procurement AI</span>
      </div>
    </div>
  );
}

export function SupplierTab({ state }: { state: WmsState }) {
  const [openVendor, setOpenVendor] = useState<string | null>(null);
  const vendor = state.vendors.find((v) => v.id === openVendor) ?? null;
  const vendorPos = vendor ? state.pos.filter((p) => p.vendorId === vendor.id) : [];

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {state.vendors.map((v) => (
          <button key={v.id} onClick={() => setOpenVendor(v.id)} className="text-left">
            <GlassCard className="h-full space-y-2 transition-transform hover:-translate-y-1 hover:neon-ring">
              <div className="flex items-center justify-between">
                <Building2 className="size-4 text-neon" />
                <Pill tone="cyan">{v.leadTimeHrs}h lead</Pill>
              </div>
              <p className="font-semibold">{v.name}</p>
              <p className="font-mono text-[11px] text-muted-foreground">{v.gstin}</p>
              <div className="flex items-center justify-between pt-1 text-xs">
                <span className="inline-flex items-center gap-1 text-neon-amber">
                  <Star className="size-3.5 fill-current" /> {v.rating}
                </span>
                <span className="font-mono">{inrCompact(v.lifetimeSpend)}</span>
              </div>
              <p className="text-[11px] text-muted-foreground">{v.unitsPurchased.toLocaleString("en-IN")} units lifetime</p>
            </GlassCard>
          </button>
        ))}
      </div>

      <GlassCard>
        <SectionTitle
          title="Dynamic PO Invoice Ledger"
          subtitle="Auto-drafted whenever the autonomous engine detects a stock-out"
          right={<Pill tone="violet"><FileText className="size-3" /> {state.pos.length} bills</Pill>}
        />
        <div className="grid gap-4 xl:grid-cols-2">
          {state.pos.map((po) => (
            <InvoiceBill key={po.id} po={po} />
          ))}
        </div>
      </GlassCard>

      <Dialog open={Boolean(vendor)} onOpenChange={(o) => !o && setOpenVendor(null)}>
        <DialogContent className="glass max-h-[85vh] overflow-y-auto sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle className="font-display">{vendor?.name}</DialogTitle>
          </DialogHeader>
          {vendor ? (
            <div className="space-y-4">
              <div className="grid gap-3 sm:grid-cols-3">
                <div className="glass-2 rounded-xl p-3">
                  <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Units purchased</p>
                  <p className="font-display text-lg font-semibold">{vendor.unitsPurchased.toLocaleString("en-IN")}</p>
                </div>
                <div className="glass-2 rounded-xl p-3">
                  <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Lifetime spend</p>
                  <p className="font-display text-lg font-semibold text-neon">{inrCompact(vendor.lifetimeSpend)}</p>
                </div>
                <div className="glass-2 rounded-xl p-3">
                  <p className="text-[11px] uppercase tracking-wider text-muted-foreground">Active SLA</p>
                  <p className="text-sm font-semibold">{vendor.sla}</p>
                </div>
              </div>
              <p className="text-xs text-muted-foreground">
                GSTIN {vendor.gstin} · {vendor.city} · rating {vendor.rating}★ · lead time {vendor.leadTimeHrs}h
              </p>
              <div className="space-y-3">
                <p className="text-sm font-semibold">Historical purchase order bills</p>
                {vendorPos.length === 0 ? (
                  <p className="text-xs text-muted-foreground">No bills raised against this vendor yet.</p>
                ) : (
                  vendorPos.map((po) => (
                    <div key={po.id} className="glass-2 flex flex-wrap items-center justify-between gap-3 rounded-xl px-4 py-3">
                      <div>
                        <p className="font-mono text-xs font-semibold">{po.id}</p>
                        <p className="text-[11px] text-muted-foreground">
                          {po.item} · {po.units} units · {timeAgo(po.createdAt)}
                        </p>
                      </div>
                      <span className="font-mono text-sm text-neon">{inr(po.total)}</span>
                    </div>
                  ))
                )}
              </div>
            </div>
          ) : null}
        </DialogContent>
      </Dialog>
    </div>
  );
}
